### ISSUE TITLE
Reduce dependencies of the npm package

### ISSUE THREAD

**Issue by jobisoft** [thunderbird/webext-compat-data#2]
The page of the npm package lists all the packages which are needed to generate the data as dependencies:
https://www.npmjs.com/package/@thunderbirdops/webext-compat-data?activeTab=dependencies

But the only real dependency should be @mdn/browser-compat-data, the others are just needed to generate the data, but the package should use the already generated json file hosted in this repo.

Is there a way to update the description page of the npm package?

**Comment by MelissaAutumn** [comment]
I can look at this next week but it should just be moving most of the dependencies over to a devDependencies key in package.json and then changing the version and publishing a new version.

https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

**Comment by jobisoft** [comment]
Thanks. That fixed it.
